/**
 * PetNudge Website - Interactive Features
 * Language toggle, FAQ accordion, sticky CTA, mobile menu
 * Supports: EN, FR, RO, ES, DE, IT, PT, JA, ZH
 */

(function() {
  'use strict';

  // ==========================================
  // Available Languages
  // ==========================================
  const languages = ['en', 'fr', 'ro', 'es', 'de', 'it', 'pt', 'ja', 'zh'];
  const languageNames = {
    en: 'English',
    fr: 'Français',
    ro: 'Română',
    es: 'Español',
    de: 'Deutsch',
    it: 'Italiano',
    pt: 'Português',
    ja: '日本語',
    zh: '中文'
  };

  // ==========================================
  // Translations
  // ==========================================
  const translations = {
    // ========== ENGLISH ==========
    en: {
      'nav.features': 'Features',
      'nav.how': 'How It Works',
      'nav.pricing': 'Pricing',
      'nav.faq': 'FAQ',
      'nav.privacy': 'Privacy',
      'nav.shop': 'Shop',
      'hero.badge': 'Pet Safety Reimagined',
      'hero.title1': 'Smart Pet ID +',
      'hero.title2': 'Lost Pet Recovery',
      'hero.subtitle': 'Create QR codes and NFC tags with the app. Anyone who finds your pet can scan and call you instantly.',
      'hero.cta1': 'Download on App Store',
      'hero.cta2': 'See How It Works',
      'problem.label': 'The Problem',
      'problem.title': 'Traditional pet ID has failed',
      'problem.subtitle': 'Microchips and engraved tags aren\'t enough when your pet goes missing.',
      'problem.1.title': 'Microchips require a vet visit',
      'problem.1.desc': 'If someone finds your pet, they need to take it to a vet or shelter with a scanner. Most people don\'t know this or won\'t do it.',
      'problem.2.title': 'Engraved tags get outdated',
      'problem.2.desc': 'Phone numbers change. Tags get worn and unreadable. You can\'t update them remotely.',
      'solution.label': 'The Solution',
      'solution.title': 'Modern pet ID that actually works',
      'solution.subtitle': 'Instant contact through technology everyone already has.',
      'solution.1.title': 'QR Code',
      'solution.1.desc': 'Finders scan with any smartphone camera. No app needed for them.',
      'solution.2.title': 'NFC Tag',
      'solution.2.desc': 'Tap to call. Works on all modern phones instantly.',
      'solution.3.title': 'Lost Mode',
      'solution.3.desc': 'Activate remotely. Finders see urgent alert with reward info.',
      'how.label': 'How It Works',
      'how.title': '3 simple steps to protect your pet',
      'how.1.title': 'Download the app & create profile',
      'how.1.desc': 'Download PetNudge on iPhone. Add your pet with photo, name, and contact number.',
      'how.2.title': 'Generate & attach tag',
      'how.2.desc': 'Print the QR code or write to an NFC tag. Attach it to the collar.',
      'how.3.title': 'If lost, enable Lost Mode',
      'how.3.desc': 'One tap shows finders an urgent alert with reward info. Track scan locations.',
      'lost.label': 'The Differentiator',
      'lost.title': 'Lost Mode changes everything',
      'lost.subtitle': 'When your pet goes missing, activate Lost Mode. Here\'s what finders see:',
      'lost.demo.alert': 'LOST PET',
      'lost.demo.alert.sub': 'This pet is reported missing',
      'lost.demo.name': 'Max',
      'lost.demo.contact': 'Tap to call owner',
      'lost.demo.phone': '+33 6 12 34 56 78',
      'lost.demo.reward': 'Reward offered for safe return',
      'lost.feature.1.title': 'Instant contact',
      'lost.feature.1.desc': 'One tap to call. No app download, no registration.',
      'lost.feature.2.title': 'Scan tracking',
      'lost.feature.2.desc': 'See when and where your tag was scanned (city-level only).',
      'lost.feature.3.title': 'Reward display',
      'lost.feature.3.desc': 'Motivate finders with optional reward message.',
      'lost.feature.4.title': 'Remote activation',
      'lost.feature.4.desc': 'Turn Lost Mode on/off from anywhere in the app.',
      'privacy.label': 'Privacy First',
      'privacy.title': 'Your data stays yours',
      'privacy.subtitle': 'We built PetNudge with privacy as a core principle.',
      'privacy.1.title': 'Health data stays on device',
      'privacy.1.desc': 'Medical records stored locally. Only pet profile (name, photo, contact) is shared when scanned.',
      'privacy.2.title': 'No public profiles',
      'privacy.2.desc': 'Finders only see contact info. No health data ever shared.',
      'privacy.3.title': 'City-level tracking',
      'privacy.3.desc': 'Scan history shows city only, not precise coordinates.',
      'features.label': 'More Than ID Tags',
      'features.title': 'Complete pet health companion',
      'features.subtitle': 'Beyond lost pet recovery, track your pet\'s complete health.',
      'features.1.title': 'Health Records',
      'features.1.desc': 'Track vaccinations, medications, weight, and vet visits.',
      'features.2.title': 'Smart Reminders',
      'features.2.desc': 'Never miss a medication dose or vaccination date.',
      'features.3.title': 'AI Assistant',
      'features.3.desc': 'Get instant guidance on symptoms and food safety.',
      'features.4.title': 'PDF Export',
      'features.4.desc': 'Generate health reports for vet visits or travel.',
      'features.5.title': 'Find Vet Clinics',
      'features.5.desc': 'Locate nearby veterinarians and emergency hospitals.',
      'features.6.title': 'Multiple Pets',
      'features.6.desc': 'Manage all your pets in one secure app.',
      'pricing.label': 'Pricing',
      'pricing.title': 'Start with 7 days free',
      'pricing.subtitle': 'Try everything. No commitment. Cancel anytime.',
      'pricing.badge': '7-Day Free Trial',
      'pricing.card.title': 'PetNudge',
      'pricing.card.subtitle': 'Full access to all features',
      'pricing.feature.1': 'QR Code & NFC tag generation',
      'pricing.feature.2': 'Lost Mode with scan tracking',
      'pricing.feature.3': 'AI health assistant',
      'pricing.feature.4': 'Unlimited pets',
      'pricing.feature.5': 'PDF health reports',
      'pricing.feature.6': 'Smart reminders',
      'pricing.plan.monthly': 'Monthly plan',
      'pricing.plan.yearly': 'Yearly plan',
      'pricing.plan.save': 'Save with annual',
      'pricing.cta': 'Start Free Trial',
      'faq.label': 'Questions',
      'faq.title': 'Frequently asked questions',
      'faq.1.q': 'Do finders need the PetNudge app?',
      'faq.1.a': 'No. Finders just scan the QR code with any smartphone camera or tap the NFC tag. No app download or registration required.',
      'faq.2.q': 'Which phones support NFC tags?',
      'faq.2.a': 'All iPhones from iPhone 7 and later, plus most Android phones from 2015 onwards. For QR codes, any smartphone with a camera works.',
      'faq.3.q': 'Does it work without internet?',
      'faq.3.a': 'The NFC tag triggers a phone call, which works without internet. QR codes open a contact card that may need data to load.',
      'faq.4.q': 'What happens when someone scans my pet\'s tag?',
      'faq.4.a': 'They see your pet\'s name and a button to call you. If Lost Mode is active, they also see an urgent alert and any reward message.',
      'faq.5.q': 'Can I use my existing microchip?',
      'faq.5.a': 'Yes! PetNudge complements microchips. We recommend using both: microchip for permanent ID, NFC/QR for instant contact.',
      'faq.6.q': 'Are the tags waterproof?',
      'faq.6.a': 'NFC stickers are water-resistant. We recommend placing them inside a protective tag holder for outdoor durability.',
      'faq.7.q': 'What if I cancel my subscription?',
      'faq.7.a': 'Your basic pet profiles remain accessible. QR codes and NFC tags continue working. Lost Mode requires an active subscription.',
      'waitlist.label': 'Coming Soon',
      'waitlist.title': 'Custom NFC Pet Tags',
      'waitlist.subtitle': 'Pre-programmed NFC tags designed for pet collars. Join the waitlist.',
      'waitlist.placeholder': 'Enter your email',
      'waitlist.btn': 'Notify Me',
      'waitlist.note': 'We\'ll email you when tags are available. No spam.',
      'footer.tagline': 'Smart pet ID and health companion for modern pet owners.',
      'footer.legal': 'Legal',
      'footer.support': 'Support',
      'footer.contact': 'Contact Us',
      'footer.copyright': '2025 PetNudge. All rights reserved.',
      'sticky.title': 'Protect your pet today',
      'sticky.subtitle': '7-day free trial, cancel anytime',
      'sticky.cta': 'Download Free'
    },

    // ========== FRENCH ==========
    fr: {
      'nav.features': 'Fonctionnalités',
      'nav.how': 'Comment ça marche',
      'nav.pricing': 'Tarifs',
      'nav.faq': 'FAQ',
      'nav.privacy': 'Confidentialité',
      'nav.shop': 'Boutique',
      'hero.badge': 'Sécurité animale réinventée',
      'hero.title1': 'Identification Intelligente +',
      'hero.title2': 'Récupération d\'Animaux Perdus',
      'hero.subtitle': 'QR codes et tags NFC permettant à quiconque trouve votre animal de vous contacter instantanément. Aucune app requise.',
      'hero.cta1': 'Télécharger sur l\'App Store',
      'hero.cta2': 'Voir comment ça marche',
      'problem.label': 'Le Problème',
      'problem.title': 'L\'identification traditionnelle a échoué',
      'problem.subtitle': 'Les puces et médailles gravées ne suffisent pas quand votre animal disparaît.',
      'problem.1.title': 'Les puces nécessitent un vétérinaire',
      'problem.1.desc': 'Si quelqu\'un trouve votre animal, il doit l\'emmener chez un vétérinaire avec un lecteur. La plupart des gens ne le font pas.',
      'problem.2.title': 'Les médailles gravées deviennent obsolètes',
      'problem.2.desc': 'Les numéros changent. Les médailles s\'usent. Impossible de les mettre à jour à distance.',
      'solution.label': 'La Solution',
      'solution.title': 'Identification moderne qui fonctionne',
      'solution.subtitle': 'Contact instantané grâce à la technologie que tout le monde possède.',
      'solution.1.title': 'QR Code',
      'solution.1.desc': 'N\'importe quel smartphone peut le scanner. Aucune app requise.',
      'solution.2.title': 'Tag NFC',
      'solution.2.desc': 'Touchez pour appeler. Fonctionne sur tous les téléphones modernes.',
      'solution.3.title': 'Mode Perdu',
      'solution.3.desc': 'Activez à distance. L\'alerte urgente s\'affiche avec la récompense.',
      'how.label': 'Comment ça marche',
      'how.title': '3 étapes simples pour protéger votre animal',
      'how.1.title': 'Créez le profil de votre animal',
      'how.1.desc': 'Ajoutez votre animal avec photo, nom et votre numéro de téléphone.',
      'how.2.title': 'Générez et attachez le tag',
      'how.2.desc': 'Imprimez le QR code ou programmez un tag NFC. Attachez-le au collier.',
      'how.3.title': 'Si perdu, activez le Mode Perdu',
      'how.3.desc': 'Un tap affiche une alerte urgente avec récompense. Suivez les scans.',
      'lost.label': 'Le Différenciateur',
      'lost.title': 'Le Mode Perdu change tout',
      'lost.subtitle': 'Quand votre animal disparaît, activez le Mode Perdu. Voici ce que voient les personnes :',
      'lost.demo.alert': 'ANIMAL PERDU',
      'lost.demo.alert.sub': 'Cet animal est signalé disparu',
      'lost.demo.name': 'Max',
      'lost.demo.contact': 'Appuyer pour appeler',
      'lost.demo.phone': '+33 6 12 34 56 78',
      'lost.demo.reward': 'Récompense offerte pour retour sain et sauf',
      'lost.feature.1.title': 'Contact instantané',
      'lost.feature.1.desc': 'Un tap pour appeler. Aucune app, aucune inscription.',
      'lost.feature.2.title': 'Suivi des scans',
      'lost.feature.2.desc': 'Voyez quand et où votre tag a été scanné (ville uniquement).',
      'lost.feature.3.title': 'Affichage récompense',
      'lost.feature.3.desc': 'Motivez les personnes avec un message de récompense optionnel.',
      'lost.feature.4.title': 'Activation à distance',
      'lost.feature.4.desc': 'Activez/désactivez le Mode Perdu depuis n\'importe où.',
      'privacy.label': 'Confidentialité d\'abord',
      'privacy.title': 'Vos données vous appartiennent',
      'privacy.subtitle': 'PetNudge est construit avec la confidentialité comme principe fondamental.',
      'privacy.1.title': 'Stockage local',
      'privacy.1.desc': 'Les dossiers de santé restent sur votre appareil. Aucun cloud requis.',
      'privacy.2.title': 'Pas de profils publics',
      'privacy.2.desc': 'Les personnes ne voient que vos coordonnées. Jamais de données de santé.',
      'privacy.3.title': 'Localisation par ville',
      'privacy.3.desc': 'L\'historique des scans montre la ville uniquement, pas les coordonnées.',
      'features.label': 'Plus que des tags',
      'features.title': 'Compagnon santé complet',
      'features.subtitle': 'Au-delà de la récupération d\'animaux perdus, suivez la santé de votre animal.',
      'features.1.title': 'Dossiers de santé',
      'features.1.desc': 'Suivez vaccinations, médicaments, poids et visites vétérinaires.',
      'features.2.title': 'Rappels intelligents',
      'features.2.desc': 'Ne manquez jamais une dose de médicament ou une vaccination.',
      'features.3.title': 'Assistant IA',
      'features.3.desc': 'Obtenez des conseils sur les symptômes et la sécurité alimentaire.',
      'features.4.title': 'Export PDF',
      'features.4.desc': 'Générez des rapports de santé pour les visites vétérinaires.',
      'features.5.title': 'Trouver des cliniques',
      'features.5.desc': 'Localisez les vétérinaires et urgences à proximité.',
      'features.6.title': 'Plusieurs animaux',
      'features.6.desc': 'Gérez tous vos animaux dans une seule app sécurisée.',
      'pricing.label': 'Tarifs',
      'pricing.title': 'Commencez avec 7 jours gratuits',
      'pricing.subtitle': 'Essayez tout. Sans engagement. Annulez à tout moment.',
      'pricing.badge': 'Essai gratuit 7 jours',
      'pricing.card.title': 'PetNudge',
      'pricing.card.subtitle': 'Accès complet à toutes les fonctionnalités',
      'pricing.feature.1': 'Génération QR Code & tag NFC',
      'pricing.feature.2': 'Mode Perdu avec suivi des scans',
      'pricing.feature.3': 'Assistant santé IA',
      'pricing.feature.4': 'Animaux illimités',
      'pricing.feature.5': 'Rapports de santé PDF',
      'pricing.feature.6': 'Rappels intelligents',
      'pricing.plan.monthly': 'Forfait mensuel',
      'pricing.plan.yearly': 'Forfait annuel',
      'pricing.plan.save': 'Économisez avec l\'annuel',
      'pricing.cta': 'Commencer l\'essai gratuit',
      'faq.label': 'Questions',
      'faq.title': 'Questions fréquentes',
      'faq.1.q': 'Les personnes qui trouvent l\'animal ont-elles besoin de l\'app ?',
      'faq.1.a': 'Non. Elles scannent simplement le QR code ou touchent le tag NFC. Aucun téléchargement ni inscription requis.',
      'faq.2.q': 'Quels téléphones supportent les tags NFC ?',
      'faq.2.a': 'Tous les iPhones à partir de l\'iPhone 7, et la plupart des téléphones Android depuis 2015.',
      'faq.3.q': 'Ça fonctionne sans internet ?',
      'faq.3.a': 'Le tag NFC déclenche un appel téléphonique, qui fonctionne sans internet.',
      'faq.4.q': 'Que se passe-t-il quand quelqu\'un scanne le tag ?',
      'faq.4.a': 'La personne voit le nom de votre animal et un bouton pour vous appeler. Si le Mode Perdu est actif, elle voit aussi l\'alerte urgente.',
      'faq.5.q': 'Puis-je utiliser ma puce existante ?',
      'faq.5.a': 'Oui ! PetNudge complète les puces. Nous recommandons les deux : puce pour l\'ID permanent, NFC/QR pour le contact instantané.',
      'faq.6.q': 'Les tags sont-ils étanches ?',
      'faq.6.a': 'Les autocollants NFC sont résistants à l\'eau. Nous recommandons un support de protection pour l\'extérieur.',
      'faq.7.q': 'Que se passe-t-il si j\'annule mon abonnement ?',
      'faq.7.a': 'Vos profils d\'animaux restent accessibles. Les tags continuent de fonctionner. Le Mode Perdu nécessite un abonnement actif.',
      'waitlist.label': 'Bientôt disponible',
      'waitlist.title': 'Tags NFC personnalisés',
      'waitlist.subtitle': 'Tags NFC pré-programmés pour les colliers. Rejoignez la liste d\'attente.',
      'waitlist.placeholder': 'Entrez votre email',
      'waitlist.btn': 'Me notifier',
      'waitlist.note': 'Nous vous enverrons un email quand les tags seront disponibles.',
      'footer.tagline': 'Identification intelligente et compagnon santé pour propriétaires d\'animaux.',
      'footer.legal': 'Légal',
      'footer.support': 'Support',
      'footer.contact': 'Nous contacter',
      'footer.copyright': '2025 PetNudge. Tous droits réservés.',
      'sticky.title': 'Protégez votre animal aujourd\'hui',
      'sticky.subtitle': 'Essai gratuit 7 jours',
      'sticky.cta': 'Télécharger gratuit'
    },

    // ========== ROMANIAN ==========
    ro: {
      'nav.features': 'Funcții',
      'nav.how': 'Cum funcționează',
      'nav.pricing': 'Prețuri',
      'nav.faq': 'Întrebări',
      'nav.privacy': 'Confidențialitate',
      'nav.shop': 'Magazin',
      'hero.badge': 'Siguranța animalelor reinventată',
      'hero.title1': 'Identificare Inteligentă +',
      'hero.title2': 'Recuperare Animale Pierdute',
      'hero.subtitle': 'Coduri QR și taguri NFC care permit oricui găsește animalul să te contacteze instant. Fără aplicație pentru găsitori.',
      'hero.cta1': 'Descarcă din App Store',
      'hero.cta2': 'Vezi cum funcționează',
      'problem.label': 'Problema',
      'problem.title': 'Identificarea tradițională a eșuat',
      'problem.subtitle': 'Microcipurile și medaliile gravate nu sunt suficiente când animalul dispare.',
      'problem.1.title': 'Microcipurile necesită vizită la veterinar',
      'problem.1.desc': 'Dacă cineva găsește animalul, trebuie să-l ducă la un veterinar cu scanner. Majoritatea oamenilor nu fac asta.',
      'problem.2.title': 'Medaliile gravate devin învechite',
      'problem.2.desc': 'Numerele de telefon se schimbă. Medaliile se uzează. Nu le poți actualiza de la distanță.',
      'solution.label': 'Soluția',
      'solution.title': 'Identificare modernă care funcționează',
      'solution.subtitle': 'Contact instant prin tehnologia pe care o are deja toată lumea.',
      'solution.1.title': 'Cod QR',
      'solution.1.desc': 'Orice cameră de smartphone îl poate scana. Fără aplicație.',
      'solution.2.title': 'Tag NFC',
      'solution.2.desc': 'Atingeți pentru a suna. Funcționează pe toate telefoanele moderne.',
      'solution.3.title': 'Mod Pierdut',
      'solution.3.desc': 'Activați de la distanță. Găsitorii văd alertă urgentă cu recompensă.',
      'how.label': 'Cum funcționează',
      'how.title': '3 pași simpli pentru a-ți proteja animalul',
      'how.1.title': 'Creează profilul animalului',
      'how.1.desc': 'Adaugă animalul cu poză, nume și numărul tău de telefon.',
      'how.2.title': 'Generează și atașează tagul',
      'how.2.desc': 'Printează codul QR sau programează un tag NFC. Atașează-l la zgardă.',
      'how.3.title': 'Dacă se pierde, activează Modul Pierdut',
      'how.3.desc': 'O singură atingere afișează alertă urgentă cu recompensă. Urmărește scanările.',
      'lost.label': 'Diferențiatorul',
      'lost.title': 'Modul Pierdut schimbă totul',
      'lost.subtitle': 'Când animalul dispare, activează Modul Pierdut. Iată ce văd găsitorii:',
      'lost.demo.alert': 'ANIMAL PIERDUT',
      'lost.demo.alert.sub': 'Acest animal este raportat dispărut',
      'lost.demo.name': 'Max',
      'lost.demo.contact': 'Atinge pentru a suna proprietarul',
      'lost.demo.phone': '+40 7XX XXX XXX',
      'lost.demo.reward': 'Recompensă oferită pentru returnare',
      'lost.feature.1.title': 'Contact instant',
      'lost.feature.1.desc': 'O atingere pentru a suna. Fără aplicație, fără înregistrare.',
      'lost.feature.2.title': 'Urmărirea scanărilor',
      'lost.feature.2.desc': 'Vezi când și unde a fost scanat tagul (doar la nivel de oraș).',
      'lost.feature.3.title': 'Afișare recompensă',
      'lost.feature.3.desc': 'Motivează găsitorii cu un mesaj opțional de recompensă.',
      'lost.feature.4.title': 'Activare la distanță',
      'lost.feature.4.desc': 'Activează/dezactivează Modul Pierdut de oriunde.',
      'privacy.label': 'Confidențialitate mai întâi',
      'privacy.title': 'Datele tale rămân ale tale',
      'privacy.subtitle': 'Am construit PetNudge cu confidențialitatea ca principiu fundamental.',
      'privacy.1.title': 'Stocare locală',
      'privacy.1.desc': 'Înregistrările de sănătate rămân pe dispozitiv. Fără cloud.',
      'privacy.2.title': 'Fără profiluri publice',
      'privacy.2.desc': 'Găsitorii văd doar informațiile de contact. Niciodată date de sănătate.',
      'privacy.3.title': 'Urmărire la nivel de oraș',
      'privacy.3.desc': 'Istoricul scanărilor arată doar orașul, nu coordonatele precise.',
      'features.label': 'Mai mult decât taguri',
      'features.title': 'Complet companion de sănătate',
      'features.subtitle': 'Dincolo de recuperarea animalelor pierdute, urmărește sănătatea completă.',
      'features.1.title': 'Dosare de sănătate',
      'features.1.desc': 'Urmărește vaccinuri, medicamente, greutate și vizite veterinare.',
      'features.2.title': 'Memento-uri inteligente',
      'features.2.desc': 'Nu mai rata niciodată o doză de medicament sau vaccin.',
      'features.3.title': 'Asistent IA',
      'features.3.desc': 'Primește îndrumare instantă despre simptome și siguranța alimentară.',
      'features.4.title': 'Export PDF',
      'features.4.desc': 'Generează rapoarte de sănătate pentru vizite veterinare.',
      'features.5.title': 'Găsește clinici',
      'features.5.desc': 'Localizează veterinari și spitale de urgență din apropiere.',
      'features.6.title': 'Mai multe animale',
      'features.6.desc': 'Gestionează toate animalele într-o singură aplicație sigură.',
      'pricing.label': 'Prețuri',
      'pricing.title': 'Începe cu 7 zile gratuite',
      'pricing.subtitle': 'Încearcă totul. Fără obligații. Anulează oricând.',
      'pricing.badge': 'Probă gratuită 7 zile',
      'pricing.card.title': 'PetNudge',
      'pricing.card.subtitle': 'Acces complet la toate funcțiile',
      'pricing.feature.1': 'Generare cod QR și tag NFC',
      'pricing.feature.2': 'Mod Pierdut cu urmărire scanări',
      'pricing.feature.3': 'Asistent de sănătate IA',
      'pricing.feature.4': 'Animale nelimitate',
      'pricing.feature.5': 'Rapoarte de sănătate PDF',
      'pricing.feature.6': 'Memento-uri inteligente',
      'pricing.plan.monthly': 'Plan lunar',
      'pricing.plan.yearly': 'Plan anual',
      'pricing.plan.save': 'Economisești cu anual',
      'pricing.cta': 'Începe proba gratuită',
      'faq.label': 'Întrebări',
      'faq.title': 'Întrebări frecvente',
      'faq.1.q': 'Au nevoie găsitorii de aplicația PetNudge?',
      'faq.1.a': 'Nu. Găsitorii scanează codul QR sau ating tagul NFC. Fără descărcare sau înregistrare.',
      'faq.2.q': 'Ce telefoane suportă taguri NFC?',
      'faq.2.a': 'Toate iPhone-urile de la iPhone 7 și majoritatea telefoanelor Android din 2015.',
      'faq.3.q': 'Funcționează fără internet?',
      'faq.3.a': 'Tagul NFC declanșează un apel telefonic, care funcționează fără internet.',
      'faq.4.q': 'Ce se întâmplă când cineva scanează tagul?',
      'faq.4.a': 'Văd numele animalului și un buton pentru a te suna. În Modul Pierdut, văd și alerta urgentă.',
      'faq.5.q': 'Pot folosi microcipul existent?',
      'faq.5.a': 'Da! PetNudge completează microcipurile. Recomandăm ambele: microcip pentru ID permanent, NFC/QR pentru contact instant.',
      'faq.6.q': 'Tagurile sunt rezistente la apă?',
      'faq.6.a': 'Autocolantele NFC sunt rezistente la apă. Recomandăm un suport protector pentru exterior.',
      'faq.7.q': 'Ce se întâmplă dacă anulez abonamentul?',
      'faq.7.a': 'Profilurile animalelor rămân accesibile. Tagurile continuă să funcționeze. Modul Pierdut necesită abonament activ.',
      'waitlist.label': 'În curând',
      'waitlist.title': 'Taguri NFC personalizate',
      'waitlist.subtitle': 'Taguri NFC pre-programate pentru zgărzi. Înscrie-te pe lista de așteptare.',
      'waitlist.placeholder': 'Introdu emailul',
      'waitlist.btn': 'Notifică-mă',
      'waitlist.note': 'Te vom anunța când tagurile sunt disponibile.',
      'footer.tagline': 'Identificare inteligentă și companion de sănătate pentru proprietarii moderni.',
      'footer.legal': 'Legal',
      'footer.support': 'Suport',
      'footer.contact': 'Contactează-ne',
      'footer.copyright': '2025 PetNudge. Toate drepturile rezervate.',
      'sticky.title': 'Protejează-ți animalul azi',
      'sticky.subtitle': 'Probă gratuită 7 zile',
      'sticky.cta': 'Descarcă gratuit'
    },

    // ========== SPANISH ==========
    es: {
      'nav.features': 'Funciones',
      'nav.how': 'Cómo funciona',
      'nav.pricing': 'Precios',
      'nav.faq': 'Preguntas',
      'nav.privacy': 'Privacidad',
      'nav.shop': 'Tienda',
      'hero.badge': 'Seguridad de mascotas reinventada',
      'hero.title1': 'Identificación Inteligente +',
      'hero.title2': 'Recuperación de Mascotas Perdidas',
      'hero.subtitle': 'Códigos QR y etiquetas NFC que permiten a quien encuentre tu mascota contactarte al instante. Sin app para quien la encuentre.',
      'hero.cta1': 'Descargar en App Store',
      'hero.cta2': 'Ver cómo funciona',
      'problem.label': 'El Problema',
      'problem.title': 'La identificación tradicional ha fallado',
      'problem.subtitle': 'Los microchips y medallas grabadas no son suficientes cuando tu mascota desaparece.',
      'problem.1.title': 'Los microchips requieren visita al veterinario',
      'problem.1.desc': 'Si alguien encuentra tu mascota, debe llevarla a un veterinario con escáner. La mayoría no lo hace.',
      'problem.2.title': 'Las medallas grabadas se desactualizan',
      'problem.2.desc': 'Los números cambian. Las medallas se desgastan. No puedes actualizarlas remotamente.',
      'solution.label': 'La Solución',
      'solution.title': 'Identificación moderna que funciona',
      'solution.subtitle': 'Contacto instantáneo mediante tecnología que todos ya tienen.',
      'solution.1.title': 'Código QR',
      'solution.1.desc': 'Cualquier cámara de smartphone puede escanearlo. Sin app requerida.',
      'solution.2.title': 'Etiqueta NFC',
      'solution.2.desc': 'Toca para llamar. Funciona en todos los teléfonos modernos.',
      'solution.3.title': 'Modo Perdido',
      'solution.3.desc': 'Activa remotamente. Quien la encuentre ve alerta urgente con recompensa.',
      'how.label': 'Cómo funciona',
      'how.title': '3 pasos simples para proteger tu mascota',
      'how.1.title': 'Crea el perfil de tu mascota',
      'how.1.desc': 'Añade tu mascota con foto, nombre y tu número de teléfono.',
      'how.2.title': 'Genera y adjunta la etiqueta',
      'how.2.desc': 'Imprime el código QR o programa una etiqueta NFC. Adjúntala al collar.',
      'how.3.title': 'Si se pierde, activa el Modo Perdido',
      'how.3.desc': 'Un toque muestra alerta urgente con recompensa. Rastrea las ubicaciones.',
      'lost.label': 'El Diferenciador',
      'lost.title': 'El Modo Perdido lo cambia todo',
      'lost.subtitle': 'Cuando tu mascota desaparece, activa el Modo Perdido. Esto es lo que ven:',
      'lost.demo.alert': 'MASCOTA PERDIDA',
      'lost.demo.alert.sub': 'Esta mascota está reportada como desaparecida',
      'lost.demo.name': 'Max',
      'lost.demo.contact': 'Toca para llamar al dueño',
      'lost.demo.phone': '+34 6XX XXX XXX',
      'lost.demo.reward': 'Se ofrece recompensa por devolución segura',
      'lost.feature.1.title': 'Contacto instantáneo',
      'lost.feature.1.desc': 'Un toque para llamar. Sin descarga de app, sin registro.',
      'lost.feature.2.title': 'Seguimiento de escaneos',
      'lost.feature.2.desc': 'Ve cuándo y dónde se escaneó tu etiqueta (solo nivel ciudad).',
      'lost.feature.3.title': 'Mostrar recompensa',
      'lost.feature.3.desc': 'Motiva a quien la encuentre con mensaje de recompensa opcional.',
      'lost.feature.4.title': 'Activación remota',
      'lost.feature.4.desc': 'Activa/desactiva el Modo Perdido desde cualquier lugar.',
      'privacy.label': 'Privacidad primero',
      'privacy.title': 'Tus datos son tuyos',
      'privacy.subtitle': 'Construimos PetNudge con la privacidad como principio fundamental.',
      'privacy.1.title': 'Almacenamiento local',
      'privacy.1.desc': 'Los registros de salud permanecen en tu dispositivo. Sin nube.',
      'privacy.2.title': 'Sin perfiles públicos',
      'privacy.2.desc': 'Solo ven tu información de contacto. Nunca datos de salud.',
      'privacy.3.title': 'Seguimiento a nivel ciudad',
      'privacy.3.desc': 'El historial muestra solo la ciudad, no coordenadas precisas.',
      'features.label': 'Más que etiquetas',
      'features.title': 'Compañero completo de salud',
      'features.subtitle': 'Más allá de recuperar mascotas perdidas, rastrea la salud completa.',
      'features.1.title': 'Registros de salud',
      'features.1.desc': 'Rastrea vacunas, medicamentos, peso y visitas veterinarias.',
      'features.2.title': 'Recordatorios inteligentes',
      'features.2.desc': 'Nunca pierdas una dosis de medicamento o vacuna.',
      'features.3.title': 'Asistente IA',
      'features.3.desc': 'Obtén orientación instantánea sobre síntomas y seguridad alimentaria.',
      'features.4.title': 'Exportar PDF',
      'features.4.desc': 'Genera informes de salud para visitas veterinarias.',
      'features.5.title': 'Encontrar clínicas',
      'features.5.desc': 'Localiza veterinarios y hospitales de emergencia cercanos.',
      'features.6.title': 'Múltiples mascotas',
      'features.6.desc': 'Gestiona todas tus mascotas en una app segura.',
      'pricing.label': 'Precios',
      'pricing.title': 'Empieza con 7 días gratis',
      'pricing.subtitle': 'Prueba todo. Sin compromiso. Cancela cuando quieras.',
      'pricing.badge': 'Prueba gratis 7 días',
      'pricing.card.title': 'PetNudge',
      'pricing.card.subtitle': 'Acceso completo a todas las funciones',
      'pricing.feature.1': 'Generación de código QR y etiqueta NFC',
      'pricing.feature.2': 'Modo Perdido con seguimiento',
      'pricing.feature.3': 'Asistente de salud IA',
      'pricing.feature.4': 'Mascotas ilimitadas',
      'pricing.feature.5': 'Informes de salud PDF',
      'pricing.feature.6': 'Recordatorios inteligentes',
      'pricing.plan.monthly': 'Plan mensual',
      'pricing.plan.yearly': 'Plan anual',
      'pricing.plan.save': 'Ahorra con el anual',
      'pricing.cta': 'Comenzar prueba gratis',
      'faq.label': 'Preguntas',
      'faq.title': 'Preguntas frecuentes',
      'faq.1.q': '¿Quien encuentra la mascota necesita la app?',
      'faq.1.a': 'No. Solo escanean el código QR o tocan la etiqueta NFC. Sin descarga ni registro.',
      'faq.2.q': '¿Qué teléfonos soportan etiquetas NFC?',
      'faq.2.a': 'Todos los iPhones desde iPhone 7 y la mayoría de Android desde 2015.',
      'faq.3.q': '¿Funciona sin internet?',
      'faq.3.a': 'La etiqueta NFC activa una llamada telefónica, que funciona sin internet.',
      'faq.4.q': '¿Qué pasa cuando alguien escanea la etiqueta?',
      'faq.4.a': 'Ven el nombre de tu mascota y un botón para llamarte. En Modo Perdido, también ven la alerta urgente.',
      'faq.5.q': '¿Puedo usar mi microchip existente?',
      'faq.5.a': 'Sí! PetNudge complementa los microchips. Recomendamos ambos: microchip para ID permanente, NFC/QR para contacto instantáneo.',
      'faq.6.q': '¿Las etiquetas son resistentes al agua?',
      'faq.6.a': 'Las pegatinas NFC son resistentes al agua. Recomendamos un soporte protector para exteriores.',
      'faq.7.q': '¿Qué pasa si cancelo mi suscripción?',
      'faq.7.a': 'Tus perfiles de mascotas permanecen accesibles. Las etiquetas siguen funcionando. El Modo Perdido requiere suscripción activa.',
      'waitlist.label': 'Próximamente',
      'waitlist.title': 'Etiquetas NFC personalizadas',
      'waitlist.subtitle': 'Etiquetas NFC preprogramadas para collares. Únete a la lista de espera.',
      'waitlist.placeholder': 'Introduce tu email',
      'waitlist.btn': 'Notifícame',
      'waitlist.note': 'Te enviaremos un email cuando estén disponibles.',
      'footer.tagline': 'Identificación inteligente y compañero de salud para dueños modernos.',
      'footer.legal': 'Legal',
      'footer.support': 'Soporte',
      'footer.contact': 'Contáctanos',
      'footer.copyright': '2025 PetNudge. Todos los derechos reservados.',
      'sticky.title': 'Protege a tu mascota hoy',
      'sticky.subtitle': 'Prueba gratis 7 días',
      'sticky.cta': 'Descargar gratis'
    },

    // ========== GERMAN ==========
    de: {
      'nav.features': 'Funktionen',
      'nav.how': 'So funktioniert\'s',
      'nav.pricing': 'Preise',
      'nav.faq': 'FAQ',
      'nav.privacy': 'Datenschutz',
      'nav.shop': 'Shop',
      'hero.badge': 'Tiersicherheit neu gedacht',
      'hero.title1': 'Intelligente Tier-ID +',
      'hero.title2': 'Verlorene Tiere wiederfinden',
      'hero.subtitle': 'QR-Codes und NFC-Tags, die jedem Finder ermöglichen, dich sofort zu kontaktieren. Keine App für Finder nötig.',
      'hero.cta1': 'Im App Store laden',
      'hero.cta2': 'So funktioniert\'s',
      'problem.label': 'Das Problem',
      'problem.title': 'Traditionelle Tier-ID hat versagt',
      'problem.subtitle': 'Mikrochips und gravierte Marken reichen nicht, wenn dein Tier verschwindet.',
      'problem.1.title': 'Mikrochips erfordern Tierarztbesuch',
      'problem.1.desc': 'Wer dein Tier findet, muss es zum Tierarzt mit Scanner bringen. Die meisten wissen das nicht oder tun es nicht.',
      'problem.2.title': 'Gravierte Marken veralten',
      'problem.2.desc': 'Telefonnummern ändern sich. Marken werden unleserlich. Du kannst sie nicht fernaktualisieren.',
      'solution.label': 'Die Lösung',
      'solution.title': 'Moderne Tier-ID, die funktioniert',
      'solution.subtitle': 'Sofortiger Kontakt durch Technologie, die jeder schon hat.',
      'solution.1.title': 'QR-Code',
      'solution.1.desc': 'Jede Smartphone-Kamera kann ihn scannen. Keine App nötig.',
      'solution.2.title': 'NFC-Tag',
      'solution.2.desc': 'Tippen zum Anrufen. Funktioniert sofort auf allen modernen Handys.',
      'solution.3.title': 'Verloren-Modus',
      'solution.3.desc': 'Fernaktivierung. Finder sehen dringende Warnung mit Belohnungsinfo.',
      'how.label': 'So funktioniert\'s',
      'how.title': '3 einfache Schritte zum Schutz deines Tieres',
      'how.1.title': 'Erstelle das Profil deines Tieres',
      'how.1.desc': 'Füge dein Tier mit Foto, Namen und deiner Telefonnummer hinzu.',
      'how.2.title': 'Generiere und befestige Tag',
      'how.2.desc': 'Drucke den QR-Code oder beschreibe einen NFC-Tag. Befestige ihn am Halsband.',
      'how.3.title': 'Bei Verlust: Verloren-Modus aktivieren',
      'how.3.desc': 'Ein Tippen zeigt Findern dringende Warnung mit Belohnung. Verfolge Scan-Orte.',
      'lost.label': 'Der Unterschied',
      'lost.title': 'Der Verloren-Modus ändert alles',
      'lost.subtitle': 'Wenn dein Tier verschwindet, aktiviere den Verloren-Modus. Das sehen Finder:',
      'lost.demo.alert': 'TIER VERMISST',
      'lost.demo.alert.sub': 'Dieses Tier wird vermisst',
      'lost.demo.name': 'Max',
      'lost.demo.contact': 'Tippen um Besitzer anzurufen',
      'lost.demo.phone': '+49 1XX XXX XXXX',
      'lost.demo.reward': 'Belohnung für sichere Rückgabe',
      'lost.feature.1.title': 'Sofortiger Kontakt',
      'lost.feature.1.desc': 'Ein Tippen zum Anrufen. Keine App, keine Registrierung.',
      'lost.feature.2.title': 'Scan-Verfolgung',
      'lost.feature.2.desc': 'Sieh wann und wo dein Tag gescannt wurde (nur Stadtebene).',
      'lost.feature.3.title': 'Belohnung anzeigen',
      'lost.feature.3.desc': 'Motiviere Finder mit optionaler Belohnungsnachricht.',
      'lost.feature.4.title': 'Fernaktivierung',
      'lost.feature.4.desc': 'Aktiviere/deaktiviere Verloren-Modus von überall.',
      'privacy.label': 'Datenschutz zuerst',
      'privacy.title': 'Deine Daten bleiben deine',
      'privacy.subtitle': 'Wir haben PetNudge mit Datenschutz als Grundprinzip gebaut.',
      'privacy.1.title': 'Lokale Speicherung',
      'privacy.1.desc': 'Gesundheitsdaten bleiben auf deinem Gerät. Keine Cloud nötig.',
      'privacy.2.title': 'Keine öffentlichen Profile',
      'privacy.2.desc': 'Finder sehen nur Kontaktdaten. Niemals Gesundheitsdaten.',
      'privacy.3.title': 'Standort auf Stadtebene',
      'privacy.3.desc': 'Scan-Verlauf zeigt nur Stadt, keine genauen Koordinaten.',
      'features.label': 'Mehr als Tags',
      'features.title': 'Kompletter Gesundheitsbegleiter',
      'features.subtitle': 'Über das Wiederfinden hinaus: Verfolge die komplette Gesundheit.',
      'features.1.title': 'Gesundheitsakten',
      'features.1.desc': 'Verfolge Impfungen, Medikamente, Gewicht und Tierarztbesuche.',
      'features.2.title': 'Intelligente Erinnerungen',
      'features.2.desc': 'Verpasse nie eine Medikamentendosis oder Impfung.',
      'features.3.title': 'KI-Assistent',
      'features.3.desc': 'Erhalte sofortige Hilfe zu Symptomen und Futtersicherheit.',
      'features.4.title': 'PDF-Export',
      'features.4.desc': 'Erstelle Gesundheitsberichte für Tierarztbesuche.',
      'features.5.title': 'Kliniken finden',
      'features.5.desc': 'Finde Tierärzte und Notfallkliniken in der Nähe.',
      'features.6.title': 'Mehrere Tiere',
      'features.6.desc': 'Verwalte alle Tiere in einer sicheren App.',
      'pricing.label': 'Preise',
      'pricing.title': 'Starte mit 7 Tagen gratis',
      'pricing.subtitle': 'Teste alles. Keine Verpflichtung. Jederzeit kündbar.',
      'pricing.badge': '7 Tage kostenlos testen',
      'pricing.card.title': 'PetNudge',
      'pricing.card.subtitle': 'Voller Zugang zu allen Funktionen',
      'pricing.feature.1': 'QR-Code & NFC-Tag Erstellung',
      'pricing.feature.2': 'Verloren-Modus mit Scan-Verfolgung',
      'pricing.feature.3': 'KI-Gesundheitsassistent',
      'pricing.feature.4': 'Unbegrenzte Tiere',
      'pricing.feature.5': 'PDF-Gesundheitsberichte',
      'pricing.feature.6': 'Intelligente Erinnerungen',
      'pricing.plan.monthly': 'Monatsplan',
      'pricing.plan.yearly': 'Jahresplan',
      'pricing.plan.save': 'Spare mit Jahresabo',
      'pricing.cta': 'Kostenlos testen',
      'faq.label': 'Fragen',
      'faq.title': 'Häufige Fragen',
      'faq.1.q': 'Brauchen Finder die PetNudge-App?',
      'faq.1.a': 'Nein. Finder scannen einfach den QR-Code oder tippen den NFC-Tag. Kein Download oder Registrierung nötig.',
      'faq.2.q': 'Welche Handys unterstützen NFC-Tags?',
      'faq.2.a': 'Alle iPhones ab iPhone 7 und die meisten Android-Handys ab 2015.',
      'faq.3.q': 'Funktioniert es ohne Internet?',
      'faq.3.a': 'Der NFC-Tag löst einen Anruf aus, der ohne Internet funktioniert.',
      'faq.4.q': 'Was passiert wenn jemand den Tag scannt?',
      'faq.4.a': 'Sie sehen den Namen deines Tieres und einen Anruf-Button. Im Verloren-Modus auch die dringende Warnung.',
      'faq.5.q': 'Kann ich meinen vorhandenen Mikrochip nutzen?',
      'faq.5.a': 'Ja! PetNudge ergänzt Mikrochips. Wir empfehlen beides: Mikrochip für permanente ID, NFC/QR für sofortigen Kontakt.',
      'faq.6.q': 'Sind die Tags wasserdicht?',
      'faq.6.a': 'NFC-Aufkleber sind wasserbeständig. Wir empfehlen eine Schutzhülle für draußen.',
      'faq.7.q': 'Was wenn ich mein Abo kündige?',
      'faq.7.a': 'Deine Tierprofile bleiben zugänglich. Tags funktionieren weiter. Der Verloren-Modus erfordert ein aktives Abo.',
      'waitlist.label': 'Demnächst',
      'waitlist.title': 'Individuelle NFC-Tier-Tags',
      'waitlist.subtitle': 'Vorprogrammierte NFC-Tags für Halsbänder. Trag dich in die Warteliste ein.',
      'waitlist.placeholder': 'E-Mail eingeben',
      'waitlist.btn': 'Benachrichtigen',
      'waitlist.note': 'Wir informieren dich, wenn Tags verfügbar sind.',
      'footer.tagline': 'Intelligente Tier-ID und Gesundheitsbegleiter für moderne Tierbesitzer.',
      'footer.legal': 'Rechtliches',
      'footer.support': 'Support',
      'footer.contact': 'Kontakt',
      'footer.copyright': '2025 PetNudge. Alle Rechte vorbehalten.',
      'sticky.title': 'Schütze dein Tier heute',
      'sticky.subtitle': '7 Tage kostenlos testen',
      'sticky.cta': 'Gratis laden'
    },

    // ========== ITALIAN ==========
    it: {
      'nav.features': 'Funzioni',
      'nav.how': 'Come funziona',
      'nav.pricing': 'Prezzi',
      'nav.faq': 'FAQ',
      'nav.privacy': 'Privacy',
      'nav.shop': 'Negozio',
      'hero.badge': 'Sicurezza animali reinventata',
      'hero.title1': 'Identificazione Intelligente +',
      'hero.title2': 'Recupero Animali Smarriti',
      'hero.subtitle': 'Codici QR e tag NFC che permettono a chiunque trovi il tuo animale di contattarti istantaneamente. Nessuna app necessaria.',
      'hero.cta1': 'Scarica dall\'App Store',
      'hero.cta2': 'Scopri come funziona',
      'problem.label': 'Il Problema',
      'problem.title': 'L\'identificazione tradizionale ha fallito',
      'problem.subtitle': 'Microchip e medagliette incise non bastano quando il tuo animale scompare.',
      'problem.1.title': 'I microchip richiedono visita veterinaria',
      'problem.1.desc': 'Chi trova il tuo animale deve portarlo da un veterinario con scanner. La maggior parte delle persone non lo fa.',
      'problem.2.title': 'Le medagliette incise diventano obsolete',
      'problem.2.desc': 'I numeri cambiano. Le medagliette si consumano. Non puoi aggiornarle da remoto.',
      'solution.label': 'La Soluzione',
      'solution.title': 'Identificazione moderna che funziona',
      'solution.subtitle': 'Contatto istantaneo tramite tecnologia che tutti già possiedono.',
      'solution.1.title': 'Codice QR',
      'solution.1.desc': 'Qualsiasi fotocamera smartphone può scansionarlo. Nessuna app richiesta.',
      'solution.2.title': 'Tag NFC',
      'solution.2.desc': 'Tocca per chiamare. Funziona su tutti i telefoni moderni.',
      'solution.3.title': 'Modalità Smarrito',
      'solution.3.desc': 'Attiva da remoto. Chi lo trova vede avviso urgente con ricompensa.',
      'how.label': 'Come funziona',
      'how.title': '3 semplici passi per proteggere il tuo animale',
      'how.1.title': 'Crea il profilo del tuo animale',
      'how.1.desc': 'Aggiungi il tuo animale con foto, nome e il tuo numero di telefono.',
      'how.2.title': 'Genera e attacca il tag',
      'how.2.desc': 'Stampa il codice QR o programma un tag NFC. Attaccalo al collare.',
      'how.3.title': 'Se si perde, attiva Modalità Smarrito',
      'how.3.desc': 'Un tocco mostra avviso urgente con ricompensa. Traccia le scansioni.',
      'lost.label': 'Il Differenziatore',
      'lost.title': 'La Modalità Smarrito cambia tutto',
      'lost.subtitle': 'Quando il tuo animale scompare, attiva la Modalità Smarrito. Ecco cosa vedono:',
      'lost.demo.alert': 'ANIMALE SMARRITO',
      'lost.demo.alert.sub': 'Questo animale è segnalato come smarrito',
      'lost.demo.name': 'Max',
      'lost.demo.contact': 'Tocca per chiamare il proprietario',
      'lost.demo.phone': '+39 3XX XXX XXXX',
      'lost.demo.reward': 'Ricompensa offerta per il ritorno sicuro',
      'lost.feature.1.title': 'Contatto istantaneo',
      'lost.feature.1.desc': 'Un tocco per chiamare. Nessuna app, nessuna registrazione.',
      'lost.feature.2.title': 'Tracciamento scansioni',
      'lost.feature.2.desc': 'Vedi quando e dove il tag è stato scansionato (solo livello città).',
      'lost.feature.3.title': 'Mostra ricompensa',
      'lost.feature.3.desc': 'Motiva chi lo trova con messaggio di ricompensa opzionale.',
      'lost.feature.4.title': 'Attivazione remota',
      'lost.feature.4.desc': 'Attiva/disattiva Modalità Smarrito da qualsiasi luogo.',
      'privacy.label': 'Privacy prima',
      'privacy.title': 'I tuoi dati restano tuoi',
      'privacy.subtitle': 'Abbiamo costruito PetNudge con la privacy come principio fondamentale.',
      'privacy.1.title': 'Archiviazione locale',
      'privacy.1.desc': 'I dati sanitari restano sul tuo dispositivo. Nessun cloud richiesto.',
      'privacy.2.title': 'Nessun profilo pubblico',
      'privacy.2.desc': 'Chi trova vede solo i contatti. Mai dati sanitari.',
      'privacy.3.title': 'Tracciamento a livello città',
      'privacy.3.desc': 'La cronologia mostra solo la città, non coordinate precise.',
      'features.label': 'Più che tag',
      'features.title': 'Compagno completo per la salute',
      'features.subtitle': 'Oltre al recupero animali smarriti, traccia la salute completa.',
      'features.1.title': 'Cartelle sanitarie',
      'features.1.desc': 'Traccia vaccini, farmaci, peso e visite veterinarie.',
      'features.2.title': 'Promemoria intelligenti',
      'features.2.desc': 'Non perdere mai una dose di farmaco o vaccino.',
      'features.3.title': 'Assistente IA',
      'features.3.desc': 'Ottieni guida istantanea su sintomi e sicurezza alimentare.',
      'features.4.title': 'Esporta PDF',
      'features.4.desc': 'Genera report sanitari per visite veterinarie.',
      'features.5.title': 'Trova cliniche',
      'features.5.desc': 'Localizza veterinari e ospedali di emergenza vicini.',
      'features.6.title': 'Più animali',
      'features.6.desc': 'Gestisci tutti i tuoi animali in un\'unica app sicura.',
      'pricing.label': 'Prezzi',
      'pricing.title': 'Inizia con 7 giorni gratis',
      'pricing.subtitle': 'Prova tutto. Senza impegno. Cancella quando vuoi.',
      'pricing.badge': 'Prova gratuita 7 giorni',
      'pricing.card.title': 'PetNudge',
      'pricing.card.subtitle': 'Accesso completo a tutte le funzioni',
      'pricing.feature.1': 'Generazione codice QR e tag NFC',
      'pricing.feature.2': 'Modalità Smarrito con tracciamento',
      'pricing.feature.3': 'Assistente sanitario IA',
      'pricing.feature.4': 'Animali illimitati',
      'pricing.feature.5': 'Report sanitari PDF',
      'pricing.feature.6': 'Promemoria intelligenti',
      'pricing.plan.monthly': 'Piano mensile',
      'pricing.plan.yearly': 'Piano annuale',
      'pricing.plan.save': 'Risparmia con l\'annuale',
      'pricing.cta': 'Inizia prova gratuita',
      'faq.label': 'Domande',
      'faq.title': 'Domande frequenti',
      'faq.1.q': 'Chi trova l\'animale ha bisogno dell\'app?',
      'faq.1.a': 'No. Basta scansionare il codice QR o toccare il tag NFC. Nessun download o registrazione.',
      'faq.2.q': 'Quali telefoni supportano i tag NFC?',
      'faq.2.a': 'Tutti gli iPhone da iPhone 7 e la maggior parte degli Android dal 2015.',
      'faq.3.q': 'Funziona senza internet?',
      'faq.3.a': 'Il tag NFC attiva una chiamata telefonica, che funziona senza internet.',
      'faq.4.q': 'Cosa succede quando qualcuno scansiona il tag?',
      'faq.4.a': 'Vedono il nome del tuo animale e un pulsante per chiamarti. In Modalità Smarrito, anche l\'avviso urgente.',
      'faq.5.q': 'Posso usare il mio microchip esistente?',
      'faq.5.a': 'Sì! PetNudge integra i microchip. Raccomandiamo entrambi: microchip per ID permanente, NFC/QR per contatto istantaneo.',
      'faq.6.q': 'I tag sono impermeabili?',
      'faq.6.a': 'Gli adesivi NFC sono resistenti all\'acqua. Raccomandiamo una custodia protettiva per esterni.',
      'faq.7.q': 'Cosa succede se cancello l\'abbonamento?',
      'faq.7.a': 'I profili animali restano accessibili. I tag continuano a funzionare. Modalità Smarrito richiede abbonamento attivo.',
      'waitlist.label': 'Prossimamente',
      'waitlist.title': 'Tag NFC personalizzati',
      'waitlist.subtitle': 'Tag NFC pre-programmati per collari. Iscriviti alla lista d\'attesa.',
      'waitlist.placeholder': 'Inserisci la tua email',
      'waitlist.btn': 'Avvisami',
      'waitlist.note': 'Ti invieremo un\'email quando i tag saranno disponibili.',
      'footer.tagline': 'Identificazione intelligente e compagno sanitario per proprietari moderni.',
      'footer.legal': 'Legale',
      'footer.support': 'Supporto',
      'footer.contact': 'Contattaci',
      'footer.copyright': '2025 PetNudge. Tutti i diritti riservati.',
      'sticky.title': 'Proteggi il tuo animale oggi',
      'sticky.subtitle': 'Prova gratuita 7 giorni',
      'sticky.cta': 'Scarica gratis'
    },

    // ========== PORTUGUESE ==========
    pt: {
      'nav.features': 'Recursos',
      'nav.how': 'Como funciona',
      'nav.pricing': 'Preços',
      'nav.faq': 'FAQ',
      'nav.privacy': 'Privacidade',
      'nav.shop': 'Loja',
      'hero.badge': 'Segurança de pets reinventada',
      'hero.title1': 'Identificação Inteligente +',
      'hero.title2': 'Recuperação de Pets Perdidos',
      'hero.subtitle': 'QR codes e tags NFC que permitem a quem encontrar seu pet contactar você instantaneamente. Sem app necessário.',
      'hero.cta1': 'Baixar na App Store',
      'hero.cta2': 'Veja como funciona',
      'problem.label': 'O Problema',
      'problem.title': 'A identificação tradicional falhou',
      'problem.subtitle': 'Microchips e medalhas gravadas não são suficientes quando seu pet desaparece.',
      'problem.1.title': 'Microchips requerem visita ao veterinário',
      'problem.1.desc': 'Se alguém encontra seu pet, precisa levá-lo a um veterinário com scanner. A maioria não faz isso.',
      'problem.2.title': 'Medalhas gravadas ficam desatualizadas',
      'problem.2.desc': 'Números mudam. Medalhas se desgastam. Você não pode atualizá-las remotamente.',
      'solution.label': 'A Solução',
      'solution.title': 'Identificação moderna que funciona',
      'solution.subtitle': 'Contato instantâneo através de tecnologia que todos já têm.',
      'solution.1.title': 'Código QR',
      'solution.1.desc': 'Qualquer câmera de smartphone pode escanear. Sem app necessário.',
      'solution.2.title': 'Tag NFC',
      'solution.2.desc': 'Toque para ligar. Funciona em todos os telefones modernos.',
      'solution.3.title': 'Modo Perdido',
      'solution.3.desc': 'Ative remotamente. Quem encontrar vê alerta urgente com recompensa.',
      'how.label': 'Como funciona',
      'how.title': '3 passos simples para proteger seu pet',
      'how.1.title': 'Crie o perfil do seu pet',
      'how.1.desc': 'Adicione seu pet com foto, nome e seu número de telefone.',
      'how.2.title': 'Gere e anexe o tag',
      'how.2.desc': 'Imprima o código QR ou programe um tag NFC. Anexe à coleira.',
      'how.3.title': 'Se perder, ative o Modo Perdido',
      'how.3.desc': 'Um toque mostra alerta urgente com recompensa. Rastreie as localizações.',
      'lost.label': 'O Diferencial',
      'lost.title': 'O Modo Perdido muda tudo',
      'lost.subtitle': 'Quando seu pet desaparece, ative o Modo Perdido. Veja o que quem encontrar vê:',
      'lost.demo.alert': 'PET PERDIDO',
      'lost.demo.alert.sub': 'Este pet está reportado como desaparecido',
      'lost.demo.name': 'Max',
      'lost.demo.contact': 'Toque para ligar para o dono',
      'lost.demo.phone': '+55 11 9XXXX-XXXX',
      'lost.demo.reward': 'Recompensa oferecida pelo retorno seguro',
      'lost.feature.1.title': 'Contato instantâneo',
      'lost.feature.1.desc': 'Um toque para ligar. Sem download de app, sem registro.',
      'lost.feature.2.title': 'Rastreamento de scans',
      'lost.feature.2.desc': 'Veja quando e onde seu tag foi escaneado (apenas nível cidade).',
      'lost.feature.3.title': 'Exibir recompensa',
      'lost.feature.3.desc': 'Motive quem encontrar com mensagem de recompensa opcional.',
      'lost.feature.4.title': 'Ativação remota',
      'lost.feature.4.desc': 'Ative/desative o Modo Perdido de qualquer lugar.',
      'privacy.label': 'Privacidade primeiro',
      'privacy.title': 'Seus dados são seus',
      'privacy.subtitle': 'Construímos o PetNudge com privacidade como princípio fundamental.',
      'privacy.1.title': 'Armazenamento local',
      'privacy.1.desc': 'Registros de saúde ficam no seu dispositivo. Sem nuvem.',
      'privacy.2.title': 'Sem perfis públicos',
      'privacy.2.desc': 'Quem encontrar vê apenas contatos. Nunca dados de saúde.',
      'privacy.3.title': 'Rastreamento por cidade',
      'privacy.3.desc': 'O histórico mostra apenas a cidade, não coordenadas precisas.',
      'features.label': 'Mais que tags',
      'features.title': 'Companheiro completo de saúde',
      'features.subtitle': 'Além da recuperação de pets perdidos, rastreie a saúde completa.',
      'features.1.title': 'Registros de saúde',
      'features.1.desc': 'Rastreie vacinas, medicamentos, peso e visitas veterinárias.',
      'features.2.title': 'Lembretes inteligentes',
      'features.2.desc': 'Nunca perca uma dose de medicamento ou vacina.',
      'features.3.title': 'Assistente IA',
      'features.3.desc': 'Obtenha orientação instantânea sobre sintomas e segurança alimentar.',
      'features.4.title': 'Exportar PDF',
      'features.4.desc': 'Gere relatórios de saúde para visitas veterinárias.',
      'features.5.title': 'Encontrar clínicas',
      'features.5.desc': 'Localize veterinários e hospitais de emergência próximos.',
      'features.6.title': 'Múltiplos pets',
      'features.6.desc': 'Gerencie todos os seus pets em um app seguro.',
      'pricing.label': 'Preços',
      'pricing.title': 'Comece com 7 dias grátis',
      'pricing.subtitle': 'Experimente tudo. Sem compromisso. Cancele quando quiser.',
      'pricing.badge': 'Teste grátis 7 dias',
      'pricing.card.title': 'PetNudge',
      'pricing.card.subtitle': 'Acesso completo a todos os recursos',
      'pricing.feature.1': 'Geração de código QR e tag NFC',
      'pricing.feature.2': 'Modo Perdido com rastreamento',
      'pricing.feature.3': 'Assistente de saúde IA',
      'pricing.feature.4': 'Pets ilimitados',
      'pricing.feature.5': 'Relatórios de saúde PDF',
      'pricing.feature.6': 'Lembretes inteligentes',
      'pricing.plan.monthly': 'Plano mensal',
      'pricing.plan.yearly': 'Plano anual',
      'pricing.plan.save': 'Economize com o anual',
      'pricing.cta': 'Começar teste grátis',
      'faq.label': 'Perguntas',
      'faq.title': 'Perguntas frequentes',
      'faq.1.q': 'Quem encontrar precisa do app PetNudge?',
      'faq.1.a': 'Não. Basta escanear o código QR ou tocar o tag NFC. Sem download ou registro.',
      'faq.2.q': 'Quais telefones suportam tags NFC?',
      'faq.2.a': 'Todos os iPhones a partir do iPhone 7 e a maioria dos Android desde 2015.',
      'faq.3.q': 'Funciona sem internet?',
      'faq.3.a': 'O tag NFC aciona uma chamada telefônica, que funciona sem internet.',
      'faq.4.q': 'O que acontece quando alguém escaneia o tag?',
      'faq.4.a': 'Eles veem o nome do seu pet e um botão para ligar. No Modo Perdido, também veem o alerta urgente.',
      'faq.5.q': 'Posso usar meu microchip existente?',
      'faq.5.a': 'Sim! PetNudge complementa microchips. Recomendamos ambos: microchip para ID permanente, NFC/QR para contato instantâneo.',
      'faq.6.q': 'Os tags são à prova d\'água?',
      'faq.6.a': 'Adesivos NFC são resistentes à água. Recomendamos proteção para uso externo.',
      'faq.7.q': 'O que acontece se eu cancelar minha assinatura?',
      'faq.7.a': 'Seus perfis de pets permanecem acessíveis. Os tags continuam funcionando. O Modo Perdido requer assinatura ativa.',
      'waitlist.label': 'Em breve',
      'waitlist.title': 'Tags NFC personalizados',
      'waitlist.subtitle': 'Tags NFC pré-programados para coleiras. Entre na lista de espera.',
      'waitlist.placeholder': 'Digite seu email',
      'waitlist.btn': 'Me avise',
      'waitlist.note': 'Enviaremos um email quando os tags estiverem disponíveis.',
      'footer.tagline': 'Identificação inteligente e companheiro de saúde para donos modernos.',
      'footer.legal': 'Legal',
      'footer.support': 'Suporte',
      'footer.contact': 'Contato',
      'footer.copyright': '2025 PetNudge. Todos os direitos reservados.',
      'sticky.title': 'Proteja seu pet hoje',
      'sticky.subtitle': 'Teste grátis 7 dias',
      'sticky.cta': 'Baixar grátis'
    },

    // ========== JAPANESE ==========
    ja: {
      'nav.features': '機能',
      'nav.how': '使い方',
      'nav.pricing': '料金',
      'nav.faq': 'よくある質問',
      'nav.privacy': 'プライバシー',
      'nav.shop': 'ショップ',
      'hero.badge': 'ペットの安全を再定義',
      'hero.title1': 'スマートペットID +',
      'hero.title2': '迷子ペット回収',
      'hero.subtitle': 'QRコードとNFCタグで、ペットを見つけた人が即座に連絡できます。発見者用のアプリは不要です。',
      'hero.cta1': 'App Storeでダウンロード',
      'hero.cta2': '使い方を見る',
      'problem.label': '問題',
      'problem.title': '従来のペットIDは機能していません',
      'problem.subtitle': 'マイクロチップと刻印タグでは、ペットが迷子になった時に不十分です。',
      'problem.1.title': 'マイクロチップは獣医への訪問が必要',
      'problem.1.desc': 'ペットを見つけた人は、スキャナーのある獣医に連れて行く必要があります。多くの人はそれをしません。',
      'problem.2.title': '刻印タグは古くなる',
      'problem.2.desc': '電話番号は変わります。タグは摩耗して読めなくなります。リモートで更新できません。',
      'solution.label': 'ソリューション',
      'solution.title': '実際に機能する現代のペットID',
      'solution.subtitle': '誰もが持っている技術で即座に連絡。',
      'solution.1.title': 'QRコード',
      'solution.1.desc': 'どのスマートフォンカメラでもスキャン可能。アプリ不要。',
      'solution.2.title': 'NFCタグ',
      'solution.2.desc': 'タップで電話。すべての最新スマホで即座に動作。',
      'solution.3.title': '迷子モード',
      'solution.3.desc': 'リモートで有効化。発見者に緊急アラートと報酬情報を表示。',
      'how.label': '使い方',
      'how.title': 'ペットを守る3つの簡単なステップ',
      'how.1.title': 'ペットのプロフィールを作成',
      'how.1.desc': '写真、名前、あなたの電話番号でペットを追加。',
      'how.2.title': 'タグを生成して取り付け',
      'how.2.desc': 'QRコードを印刷またはNFCタグに書き込み。首輪に取り付け。',
      'how.3.title': '迷子になったら迷子モードを有効に',
      'how.3.desc': 'ワンタップで緊急アラートと報酬を表示。スキャン場所を追跡。',
      'lost.label': '差別化ポイント',
      'lost.title': '迷子モードがすべてを変える',
      'lost.subtitle': 'ペットがいなくなったら、迷子モードを有効にします。発見者が見るもの：',
      'lost.demo.alert': '迷子ペット',
      'lost.demo.alert.sub': 'このペットは迷子として報告されています',
      'lost.demo.name': 'マックス',
      'lost.demo.contact': 'タップして飼い主に電話',
      'lost.demo.phone': '+81 90-XXXX-XXXX',
      'lost.demo.reward': '無事返還の報酬あり',
      'lost.feature.1.title': '即座の連絡',
      'lost.feature.1.desc': 'ワンタップで電話。アプリのダウンロードも登録も不要。',
      'lost.feature.2.title': 'スキャン追跡',
      'lost.feature.2.desc': 'タグがスキャンされた日時と場所を確認（市レベルのみ）。',
      'lost.feature.3.title': '報酬表示',
      'lost.feature.3.desc': 'オプションの報酬メッセージで発見者を動機付け。',
      'lost.feature.4.title': 'リモート有効化',
      'lost.feature.4.desc': 'どこからでもアプリで迷子モードをオン/オフ。',
      'privacy.label': 'プライバシー優先',
      'privacy.title': 'あなたのデータはあなたのもの',
      'privacy.subtitle': 'プライバシーを核心原則としてPetNudgeを構築しました。',
      'privacy.1.title': 'ローカル優先ストレージ',
      'privacy.1.desc': '健康記録はデバイスに保存。クラウド不要。',
      'privacy.2.title': '公開プロフィールなし',
      'privacy.2.desc': '発見者には連絡先のみ表示。健康データは決して共有しません。',
      'privacy.3.title': '市レベルの追跡',
      'privacy.3.desc': 'スキャン履歴は市のみを表示、正確な座標ではありません。',
      'features.label': 'タグ以上のもの',
      'features.title': '完全なペット健康コンパニオン',
      'features.subtitle': '迷子回収を超えて、ペットの完全な健康を追跡。',
      'features.1.title': '健康記録',
      'features.1.desc': 'ワクチン、薬、体重、獣医訪問を追跡。',
      'features.2.title': 'スマートリマインダー',
      'features.2.desc': '薬の投与やワクチンを絶対に忘れない。',
      'features.3.title': 'AIアシスタント',
      'features.3.desc': '症状や食品安全に関する即座のガイダンス。',
      'features.4.title': 'PDFエクスポート',
      'features.4.desc': '獣医訪問用の健康レポートを生成。',
      'features.5.title': 'クリニックを探す',
      'features.5.desc': '近くの獣医や緊急病院を探す。',
      'features.6.title': '複数のペット',
      'features.6.desc': 'すべてのペットを1つの安全なアプリで管理。',
      'pricing.label': '料金',
      'pricing.title': '7日間無料で開始',
      'pricing.subtitle': 'すべてをお試し。縛りなし。いつでもキャンセル。',
      'pricing.badge': '7日間無料トライアル',
      'pricing.card.title': 'PetNudge',
      'pricing.card.subtitle': 'すべての機能へのフルアクセス',
      'pricing.feature.1': 'QRコード&NFCタグ生成',
      'pricing.feature.2': 'スキャン追跡付き迷子モード',
      'pricing.feature.3': 'AI健康アシスタント',
      'pricing.feature.4': '無制限のペット',
      'pricing.feature.5': 'PDF健康レポート',
      'pricing.feature.6': 'スマートリマインダー',
      'pricing.plan.monthly': '月額プラン',
      'pricing.plan.yearly': '年間プラン',
      'pricing.plan.save': '年間でお得に',
      'pricing.cta': '無料トライアルを開始',
      'faq.label': '質問',
      'faq.title': 'よくある質問',
      'faq.1.q': '発見者はPetNudgeアプリが必要ですか？',
      'faq.1.a': 'いいえ。QRコードをスキャンするかNFCタグをタップするだけ。ダウンロードも登録も不要。',
      'faq.2.q': 'どの電話がNFCタグに対応していますか？',
      'faq.2.a': 'iPhone 7以降のすべてのiPhoneと、2015年以降のほとんどのAndroid。',
      'faq.3.q': 'インターネットなしで動作しますか？',
      'faq.3.a': 'NFCタグは電話をかけます。これはインターネットなしで動作します。',
      'faq.4.q': '誰かがタグをスキャンすると何が起こりますか？',
      'faq.4.a': 'ペットの名前と電話ボタンが表示されます。迷子モードでは緊急アラートも表示。',
      'faq.5.q': '既存のマイクロチップを使用できますか？',
      'faq.5.a': 'はい！PetNudgeはマイクロチップを補完します。両方の使用を推奨：マイクロチップは永久ID、NFC/QRは即座の連絡用。',
      'faq.6.q': 'タグは防水ですか？',
      'faq.6.a': 'NFCステッカーは耐水性があります。屋外使用には保護ケースを推奨。',
      'faq.7.q': 'サブスクリプションをキャンセルしたらどうなりますか？',
      'faq.7.a': 'ペットプロフィールはアクセス可能なまま。タグは機能し続けます。迷子モードにはアクティブなサブスクリプションが必要。',
      'waitlist.label': '近日公開',
      'waitlist.title': 'カスタムNFCペットタグ',
      'waitlist.subtitle': '首輪用のプログラム済みNFCタグ。ウェイトリストに参加。',
      'waitlist.placeholder': 'メールを入力',
      'waitlist.btn': '通知する',
      'waitlist.note': 'タグが利用可能になったらメールでお知らせします。',
      'footer.tagline': '現代のペットオーナーのためのスマートペットIDと健康コンパニオン。',
      'footer.legal': '法的情報',
      'footer.support': 'サポート',
      'footer.contact': 'お問い合わせ',
      'footer.copyright': '2025 PetNudge. 全著作権所有.',
      'sticky.title': '今日ペットを守る',
      'sticky.subtitle': '7日間無料トライアル',
      'sticky.cta': '無料ダウンロード'
    },

    // ========== CHINESE (Simplified) ==========
    zh: {
      'nav.features': '功能',
      'nav.how': '使用方法',
      'nav.pricing': '价格',
      'nav.faq': '常见问题',
      'nav.privacy': '隐私',
      'nav.shop': '商店',
      'hero.badge': '重新定义宠物安全',
      'hero.title1': '智能宠物身份证 +',
      'hero.title2': '丢失宠物找回',
      'hero.subtitle': '二维码和NFC标签让任何找到您宠物的人即时联系您。发现者无需应用程序。',
      'hero.cta1': '在App Store下载',
      'hero.cta2': '查看使用方法',
      'problem.label': '问题',
      'problem.title': '传统宠物身份证已经失败',
      'problem.subtitle': '当您的宠物走失时，芯片和刻字吊牌是不够的。',
      'problem.1.title': '芯片需要去兽医',
      'problem.1.desc': '如果有人找到您的宠物，他们需要带它去有扫描仪的兽医处。大多数人不会这样做。',
      'problem.2.title': '刻字吊牌会过时',
      'problem.2.desc': '电话号码会变。吊牌会磨损。您无法远程更新它们。',
      'solution.label': '解决方案',
      'solution.title': '真正有效的现代宠物身份证',
      'solution.subtitle': '通过每个人都有的技术即时联系。',
      'solution.1.title': '二维码',
      'solution.1.desc': '任何智能手机相机都可以扫描。无需应用程序。',
      'solution.2.title': 'NFC标签',
      'solution.2.desc': '轻触拨打电话。在所有现代手机上即时工作。',
      'solution.3.title': '丢失模式',
      'solution.3.desc': '远程激活。发现者看到紧急警报和悬赏信息。',
      'how.label': '使用方法',
      'how.title': '保护宠物的3个简单步骤',
      'how.1.title': '创建宠物档案',
      'how.1.desc': '添加宠物的照片、名字和您的电话号码。',
      'how.2.title': '生成并附上标签',
      'how.2.desc': '打印二维码或写入NFC标签。附在项圈上。',
      'how.3.title': '丢失时启用丢失模式',
      'how.3.desc': '一键显示紧急警报和悬赏。追踪扫描位置。',
      'lost.label': '差异化优势',
      'lost.title': '丢失模式改变一切',
      'lost.subtitle': '当您的宠物走失时，激活丢失模式。以下是发现者看到的内容：',
      'lost.demo.alert': '宠物走失',
      'lost.demo.alert.sub': '此宠物已被报告走失',
      'lost.demo.name': 'Max',
      'lost.demo.contact': '轻触拨打主人电话',
      'lost.demo.phone': '+86 1XX XXXX XXXX',
      'lost.demo.reward': '提供安全归还悬赏',
      'lost.feature.1.title': '即时联系',
      'lost.feature.1.desc': '一键拨打电话。无需下载应用或注册。',
      'lost.feature.2.title': '扫描追踪',
      'lost.feature.2.desc': '查看标签被扫描的时间和地点（仅城市级别）。',
      'lost.feature.3.title': '显示悬赏',
      'lost.feature.3.desc': '用可选的悬赏信息激励发现者。',
      'lost.feature.4.title': '远程激活',
      'lost.feature.4.desc': '从任何地方在应用中开启/关闭丢失模式。',
      'privacy.label': '隐私优先',
      'privacy.title': '您的数据归您所有',
      'privacy.subtitle': '我们以隐私为核心原则构建了PetNudge。',
      'privacy.1.title': '本地优先存储',
      'privacy.1.desc': '健康记录保存在您的设备上。无需云端。',
      'privacy.2.title': '无公开档案',
      'privacy.2.desc': '发现者只看到联系信息。从不分享健康数据。',
      'privacy.3.title': '城市级追踪',
      'privacy.3.desc': '扫描历史只显示城市，不显示精确坐标。',
      'features.label': '不只是标签',
      'features.title': '完整的宠物健康伴侣',
      'features.subtitle': '除了找回丢失宠物，还可追踪宠物的完整健康。',
      'features.1.title': '健康记录',
      'features.1.desc': '追踪疫苗、药物、体重和兽医就诊。',
      'features.2.title': '智能提醒',
      'features.2.desc': '永不错过药物剂量或疫苗接种日期。',
      'features.3.title': 'AI助手',
      'features.3.desc': '获取关于症状和食品安全的即时指导。',
      'features.4.title': 'PDF导出',
      'features.4.desc': '为兽医就诊生成健康报告。',
      'features.5.title': '查找诊所',
      'features.5.desc': '定位附近的兽医和紧急医院。',
      'features.6.title': '多只宠物',
      'features.6.desc': '在一个安全的应用中管理所有宠物。',
      'pricing.label': '价格',
      'pricing.title': '7天免费开始',
      'pricing.subtitle': '尝试所有功能。无需承诺。随时取消。',
      'pricing.badge': '7天免费试用',
      'pricing.card.title': 'PetNudge',
      'pricing.card.subtitle': '完全访问所有功能',
      'pricing.feature.1': '二维码和NFC标签生成',
      'pricing.feature.2': '带扫描追踪的丢失模式',
      'pricing.feature.3': 'AI健康助手',
      'pricing.feature.4': '无限宠物',
      'pricing.feature.5': 'PDF健康报告',
      'pricing.feature.6': '智能提醒',
      'pricing.plan.monthly': '月度计划',
      'pricing.plan.yearly': '年度计划',
      'pricing.plan.save': '年付更省钱',
      'pricing.cta': '开始免费试用',
      'faq.label': '问题',
      'faq.title': '常见问题',
      'faq.1.q': '发现者需要PetNudge应用吗？',
      'faq.1.a': '不需要。只需扫描二维码或轻触NFC标签。无需下载或注册。',
      'faq.2.q': '哪些手机支持NFC标签？',
      'faq.2.a': 'iPhone 7及以后的所有iPhone，以及2015年以来的大多数Android手机。',
      'faq.3.q': '没有网络能用吗？',
      'faq.3.a': 'NFC标签触发电话呼叫，无需网络即可工作。',
      'faq.4.q': '有人扫描标签时会发生什么？',
      'faq.4.a': '他们看到宠物名称和拨打电话按钮。在丢失模式下，还会看到紧急警报。',
      'faq.5.q': '我可以使用现有的芯片吗？',
      'faq.5.a': '可以！PetNudge补充芯片。我们推荐两者都用：芯片作为永久ID，NFC/二维码用于即时联系。',
      'faq.6.q': '标签防水吗？',
      'faq.6.a': 'NFC贴纸防水。我们建议户外使用时加保护套。',
      'faq.7.q': '如果取消订阅会怎样？',
      'faq.7.a': '宠物档案仍可访问。标签继续工作。丢失模式需要有效订阅。',
      'waitlist.label': '即将推出',
      'waitlist.title': '定制NFC宠物标签',
      'waitlist.subtitle': '为项圈预编程的NFC标签。加入等候名单。',
      'waitlist.placeholder': '输入您的邮箱',
      'waitlist.btn': '通知我',
      'waitlist.note': '标签可用时我们会发送邮件通知您。',
      'footer.tagline': '现代宠物主人的智能宠物身份证和健康伴侣。',
      'footer.legal': '法律信息',
      'footer.support': '支持',
      'footer.contact': '联系我们',
      'footer.copyright': '2025 PetNudge。保留所有权利。',
      'sticky.title': '今天保护您的宠物',
      'sticky.subtitle': '7天免费试用',
      'sticky.cta': '免费下载'
    }
  };

  // ==========================================
  // State
  // ==========================================
  let currentLang = localStorage.getItem('petnudge-lang') || detectLanguage();

  function detectLanguage() {
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('fr')) return 'fr';
    if (browserLang.startsWith('ro')) return 'ro';
    if (browserLang.startsWith('es')) return 'es';
    if (browserLang.startsWith('de')) return 'de';
    if (browserLang.startsWith('it')) return 'it';
    if (browserLang.startsWith('pt')) return 'pt';
    if (browserLang.startsWith('ja')) return 'ja';
    if (browserLang.startsWith('zh')) return 'zh';
    return 'en';
  }

  // ==========================================
  // DOM Ready
  // ==========================================
  document.addEventListener('DOMContentLoaded', function() {
    initLanguage();
    initFAQ();
    initStickyCTA();
    initMobileMenu();
    initSmoothScroll();
  });

  // ==========================================
  // Language Toggle (cycles through languages)
  // ==========================================
  function initLanguage() {
    setLanguage(currentLang);
    updateLangToggle();

    const langToggle = document.getElementById('lang-toggle');
    if (langToggle) {
      langToggle.addEventListener('click', function() {
        const currentIndex = languages.indexOf(currentLang);
        const nextIndex = (currentIndex + 1) % languages.length;
        currentLang = languages[nextIndex];
        localStorage.setItem('petnudge-lang', currentLang);
        setLanguage(currentLang);
        updateLangToggle();
      });
    }
  }

  function setLanguage(lang) {
    if (!translations[lang]) lang = 'en';
    document.documentElement.lang = lang;

    document.querySelectorAll('[data-i18n]').forEach(function(el) {
      const key = el.getAttribute('data-i18n');
      if (translations[lang] && translations[lang][key]) {
        el.textContent = translations[lang][key];
      }
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(function(el) {
      const key = el.getAttribute('data-i18n-placeholder');
      if (translations[lang] && translations[lang][key]) {
        el.placeholder = translations[lang][key];
      }
    });
  }

  function updateLangToggle() {
    const langText = document.getElementById('lang-text');
    if (langText) {
      langText.textContent = currentLang.toUpperCase();
    }
  }

  // ==========================================
  // FAQ Accordion
  // ==========================================
  function initFAQ() {
    const faqItems = document.querySelectorAll('.faq__item');
    faqItems.forEach(function(item) {
      const question = item.querySelector('.faq__question');
      question.addEventListener('click', function() {
        const isOpen = item.classList.contains('is-open');
        faqItems.forEach(function(otherItem) {
          otherItem.classList.remove('is-open');
        });
        if (!isOpen) {
          item.classList.add('is-open');
        }
      });
    });
  }

  // ==========================================
  // Sticky CTA
  // ==========================================
  function initStickyCTA() {
    const stickyCTA = document.querySelector('.sticky-cta');
    const hero = document.querySelector('.hero');
    if (!stickyCTA || !hero) return;

    const observer = new IntersectionObserver(function(entries) {
      entries.forEach(function(entry) {
        if (entry.isIntersecting) {
          stickyCTA.classList.remove('is-visible');
        } else {
          stickyCTA.classList.add('is-visible');
        }
      });
    }, { threshold: 0, rootMargin: '-100px 0px 0px 0px' });

    observer.observe(hero);
  }

  // ==========================================
  // Mobile Menu
  // ==========================================
  function initMobileMenu() {
    const menuBtn = document.getElementById('menu-btn');
    const menuClose = document.getElementById('menu-close');
    const mobileMenu = document.getElementById('mobile-menu');
    const mobileLinks = document.querySelectorAll('.mobile-menu__link');

    if (!menuBtn || !mobileMenu) return;

    menuBtn.addEventListener('click', function() {
      mobileMenu.classList.add('is-open');
      document.body.style.overflow = 'hidden';
    });

    if (menuClose) {
      menuClose.addEventListener('click', closeMenu);
    }

    mobileLinks.forEach(function(link) {
      link.addEventListener('click', closeMenu);
    });

    function closeMenu() {
      mobileMenu.classList.remove('is-open');
      document.body.style.overflow = '';
    }
  }

  // ==========================================
  // Smooth Scroll
  // ==========================================
  function initSmoothScroll() {
    document.querySelectorAll('a[href^="#"]').forEach(function(anchor) {
      anchor.addEventListener('click', function(e) {
        const targetId = this.getAttribute('href');
        if (targetId === '#') return;

        const target = document.querySelector(targetId);
        if (target) {
          e.preventDefault();
          const headerHeight = document.querySelector('.header').offsetHeight;
          const targetPosition = target.getBoundingClientRect().top + window.pageYOffset - headerHeight - 20;

          window.scrollTo({
            top: targetPosition,
            behavior: 'smooth'
          });
        }
      });
    });
  }

  // ==========================================
  // Waitlist Form
  // ==========================================
  window.handleWaitlist = function(e) {
    e.preventDefault();
    const email = document.getElementById('waitlist-email').value;
    if (email) {
      window.location.href = 'mailto:tags@petnudge.fr?subject=NFC Tag Waitlist&body=Please add me to the NFC tag waitlist. Email: ' + encodeURIComponent(email);
    }
  };

})();
